filename = "test"

library(data.table)
# The square LD r2 file generated by Plink
ld = fread("r2.ld")
ld = as.matrix(ld)

# A single-column file specifying which category each SNP belongs to
# Like the modelSNPs file used by BOLT
snp = read.table(paste(filename,"bolt.modelSnps.txt", sep="."))

weight = unique(snp[,2])
scores = matrix(nrow=nrow(ld),ncol=length(weight))
colnames(scores) = weight
num = rep(0,length(weight))
for(j in 1:length(weight)) {
	idx = which(snp[,2] == weight[j])
        num_na = sum(is.na(ld[1,idx]))
        num[j] = length(idx) - num_na
}
ld[is.na(ld)] = 0
for(j in 1:length(weight)) {
	idx = which(snp[,2] == weight[j])
	scores[,j] = rowSums(ld[,idx])
}
scores = rbind(num,scores)
write.table(scores, file=paste(filename,"ldsc",sep="."), quote=F, row.names=F, col.names=T)
