site_name: MPH
site_author: Jicai Jiang
site_description: MINQUE for Partitioning Heritability
copyright: "MPH is licensed under the <a href='https://github.com/jiang18/mph/blob/main/LICENSE'>GPL-3.0 license</a>"

theme:
  name: null
  custom_dir: 'cinder'
  colorscheme: github
  analytics:
    gtag: G-K4MRX3DSPN

nav:
  - Home: index.md
  - Install: install.md
  - Documentation: options.md
  - Examples: examples.md
  - Performance: performance.md
  - Utilities: util.md

markdown_extensions:
  - attr_list
  - footnotes

plugins:
  - search
